### ISSUE TITLE
Creating the home page and navigation guide

### ISSUE THREAD

**Issue by abbaskal** [Abbas-Kalantari/interactive-Covid-19-dashboard#3]
# Home Page
for homepage we need to have the followings:

- Introduction of the dashboard
- Introducing different sections (country_based, overview and etc)
- Mentioning the developers and their contacts
- Mentioning the reference for the data ( here is the [link](https://covid.ourworldindata.org/data/owid-covid-data.csv) )
- We need some decoration with markdown :smile:

**Comment by ZeynepRuveyda** [comment]
Yes, sure I will write these sections after checking my deepnote codes.

**Comment by joelmak** [comment]
Thanks for this Abbas! No worries, I'll work on this part this eve :)

**Comment by ZeynepRuveyda** [comment]
completed!
